[package]
name = "MiniCrosspaths"
namespace = "doombubbles"
description = "Adds a number of mini two-upgrade Paths++ paths for towers."
websiteUrl = "https://github.com/doombubbles/mini-crosspaths"

[package.dependencies]
LavaGang-MelonLoader = "0.7.3"
doombubbles-Btd6ModHelper = "3.6.5"
doombubbles-PathsPlusPlus = "1.2.2"

[build]
icon = "./Icon.png"
readme = "./README.md"
outdir = "bin"

[[build.copy]]
source = "./bin/Release/MiniCrosspaths.dll"
target = "MiniCrosspaths.dll"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = ["bloons-td-6"]
categories = ["mods"]
